name: tvmaze
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_splash_screen: ^1.3.0
  custom_rating_bar: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  lottie: ^3.1.3
  persistent_bottom_nav_bar_v2: ^5.3.1
  sizer: ^3.0.3
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
